-- Modelo inicial PostgreSQL para o projeto Pôster do Dia.
-- Adaptar ao framework/backend escolhido e revisar com a equipe antes de produção.

CREATE TABLE filmes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tmdb_id INTEGER UNIQUE,
    titulo VARCHAR(200) NOT NULL,
    ano_lancamento SMALLINT,
    diretor VARCHAR(160),
    sinopse TEXT,
    poster_url TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_filmes_ano CHECK (
        ano_lancamento IS NULL OR ano_lancamento BETWEEN 1888 AND 2100
    )
);

CREATE TABLE generos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE filme_genero (
    filme_id BIGINT NOT NULL REFERENCES filmes(id) ON DELETE CASCADE,
    genero_id BIGINT NOT NULL REFERENCES generos(id) ON DELETE RESTRICT,
    PRIMARY KEY (filme_id, genero_id)
);

CREATE TABLE administradores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    email VARCHAR(180) NOT NULL UNIQUE,
    senha_hash TEXT NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessoes_admin (
    id UUID PRIMARY KEY,
    administrador_id BIGINT NOT NULL REFERENCES administradores(id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL UNIQUE,
    expira_em TIMESTAMPTZ NOT NULL,
    revogada_em TIMESTAMPTZ,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE desafios_diarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filme_id BIGINT NOT NULL REFERENCES filmes(id) ON DELETE RESTRICT,
    data_desafio DATE NOT NULL UNIQUE,
    criado_por_admin_id BIGINT REFERENCES administradores(id) ON DELETE SET NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE partidas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desafio_diario_id BIGINT NOT NULL REFERENCES desafios_diarios(id) ON DELETE RESTRICT,
    jogador_uuid UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'EM_ANDAMENTO',
    tentativas_utilizadas SMALLINT NOT NULL DEFAULT 0,
    iniciado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finalizado_em TIMESTAMPTZ,
    CONSTRAINT ck_partidas_status CHECK (
        status IN ('EM_ANDAMENTO', 'VITORIA', 'DERROTA')
    ),
    CONSTRAINT ck_partidas_tentativas CHECK (
        tentativas_utilizadas BETWEEN 0 AND 6
    ),
    CONSTRAINT uq_partida_por_jogador_desafio UNIQUE (desafio_diario_id, jogador_uuid)
);

CREATE TABLE tentativas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partida_id BIGINT NOT NULL REFERENCES partidas(id) ON DELETE CASCADE,
    filme_palpite_id BIGINT NOT NULL REFERENCES filmes(id) ON DELETE RESTRICT,
    numero SMALLINT NOT NULL,
    acertou BOOLEAN NOT NULL,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_tentativas_numero CHECK (numero BETWEEN 1 AND 6),
    CONSTRAINT uq_tentativa_por_numero UNIQUE (partida_id, numero)
);

-- Índices para filtros usuais e consultas de relatório.
CREATE INDEX idx_filmes_titulo ON filmes (titulo);
CREATE INDEX idx_filmes_ano ON filmes (ano_lancamento);
CREATE INDEX idx_filme_genero_genero ON filme_genero (genero_id);
CREATE INDEX idx_desafios_filme ON desafios_diarios (filme_id);
CREATE INDEX idx_partidas_desafio_status ON partidas (desafio_diario_id, status);
CREATE INDEX idx_partidas_jogador ON partidas (jogador_uuid);
CREATE INDEX idx_tentativas_filme ON tentativas (filme_palpite_id);

-- Regras que dependem de várias linhas (ex.: não aceitar palpites após finalizar,
-- atualizar tentativas_utilizadas/status em transação, bloquear remoção de filme
-- agendado para hoje/futuro) devem ser garantidas pela lógica da API ou por triggers.
